amcl:
  ros__parameters:
    # General parameters
    use_map_topic: true
    map_topic: /map
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    scan_topic: /scan

    # Localization Parameters
    update_min_d: 0.02
    update_min_a: 0.02
    max_particles: 500
    min_particles: 500
    laser_max_range: 30.0
    laser_min_range: 0.1
    laser_likelihood_max_dist: 2.0
    tf_broadcast: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    save_pose_rate: 0.5
    transform_tolerance: 1.0
    recovery_behaviors:
      - name: "clear_costmap_recovery"
        type: "ClearCostmapRecovery"
    local_costmap:
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
    global_costmap:
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
