# Global planner parameters
planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.0
      use_astar: false
      max_planner_iterations: 500

# Local planner parameters
controller_server:
  ros__parameters:
    controller_plugins: ["SimplePlanner"]
    SimplePlanner:
      plugin: "nav2_dwb_controller/DWBLocalPlanner"
      max_vel_x: 0.5
      min_vel_x: 0.0
      max_vel_y: 0.0
      max_rotational_vel: 1.0
      acc_lim_x: 1.0
      acc_lim_y: 0.0
      acc_lim_th: 2.0

# Behavior Tree parameters
bt_navigator:
  ros__parameters:
    behavior_tree_plugin: "nav2_behavior_tree/BehaviorTreeNavigator"
    default_tree: "navigate_w_replanning.xml"

# Collision monitor parameters (optional)
collision_monitor:
  ros__parameters:
    max_obstacle_distance: 2.0
    obstacle_range: 1.5

# Velocity smoother parameters (optional)
velocity_smoother:
  ros__parameters:
    smoothing_algorithm: "catmull_rom"
    max_velocity: 0.5
